services:
  auth-db:
    container_name: auth_db
    image: postgres:16
    environment:
      - POSTGRES_USER=jrdev
      - POSTGRES_DB=auth_db
      - POSTGRES_PASSWORD=mypass123456
    ports:
      - 5432:5432
    networks:
      - local-network

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    ports:
      - "5100:5100"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      AppConfig__Port: 5100
      AppConfig__Service: Auth
      AppConfig__Status: Running
      AppConfig__ConnectionString: Host=auth-db;Port=5432;Database=auth_db;Username=jrdev;Password=mypass123456
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    external: true